### ISSUE TITLE
When i compile your project, it cause a error.

### ISSUE THREAD

**Issue by 244986830** [zhulingbiezhi/cef-chrome#1]
_Error	2994	error C2039: 'Run' : is not a member of 'CCefWindow'	D:\study\CEF\cef-chrome-master\sourceCode\QCefView\src\QCefView.cpp	61	1	QCefView_
can you teach me how to compile it? Thank you!

**Comment by zhulingbiezhi** [comment]
sorry, it's a mistake! This is my test code, it has fixed now. Please pull the code again.
